<?php

namespace Database\Seeders;

use App\Models\Confession;
use Illuminate\Database\Seeder;
use Webpatser\Countries\Countries as CountryModel;

class ConfessionSeeder extends Seeder
{
    public function run(): void
    {
        $countryCodes = ['UA', 'DE', 'PL', 'RO'];
        $countries = CountryModel::whereIn('iso_3166_2', $countryCodes)
            ->pluck('iso_3166_2', 'iso_3166_2')
            ->toArray();

        if (empty($countries)) {
            \Log::error('Countries not found. Run CountriesSeeder first.');

            return;
        }

        $confession1 = Confession::create([
            'name' => [
                'uk' => 'Православна церква Київського патріархату',
                'en' => 'Orthodox Church of the Kyiv Patriarchate',
                'de' => 'Orthodoxe Kirche des Kiewer Patriarchats',
                'ro' => 'Biserica Ortodoxă a Patriarhatului de Kiev',
                'ka' => 'კიევის საპატრიარქოს მართლმადიდებელი ეკლესია',
            ],
            'full_name' => [
                'uk' => 'Українська православна церква Київського патріархату',
                'en' => 'Ukrainian Orthodox Church of the Kyiv Patriarchate',
                'de' => 'Ukrainische Orthodoxe Kirche des Kiewer Patriarchats',
                'ro' => 'Biserica Ortodoxă Ucraineană a Patriarhatului de Kiev',
                'ka' => 'უკრაინის მართლმადიდებელი ეკლესია კიევის საპატრიარქოსი',
            ],
            'description' => [
                'uk' => 'Українська православна церква Київського патріархату (УПЦ-КП) була заснована у 1992 році. Вона веде свій духовний спадок від Хрещення Київської Русі у 988 році. Церква виникла після розколу з Московським Патріархатом через прагнення до повністю незалежної, автокефальної Української Церкви. Кафедральним собором церкви є історичний Володимирський собор у Києві, що є потужним символом української духовної суверенності. Довгий час церкву очолював Патріарх Філарет (Денисенко). Хоча УПЦ-КП приєдналася до об’єднавчого руху, що створив Православну Церкву України (ПЦУ) у 2018 році, вона пізніше була повторно зареєстрована, підтверджуючи своє окреме існування. Церква вважає себе законною наступницею стародавньої Київської митрополії. Незважаючи на складні питання канонічного визнання у світовій спільноті, УПЦ-КП залишається однією з найбільших православних конфесій в Україні. Вона здійснює всі традиційні східно-православні обряди та служби. Ми проводимо обряди, приймаємо замовлення на записки і ставимо свічки згідно з візантійською традицією.',
                'en' => 'The Ukrainian Orthodox Church of the Kyiv Patriarchate (UOC-KP) was established in 1992, tracing its spiritual heritage back to the Christianization of Kyivan Rus\' in 988. It emerged following a split from the Russian Orthodox Church, motivated by the desire for a fully independent, autocephalous Ukrainian Church. The church\'s mother see is the historic St. Volodymyr\'s Cathedral in Kyiv, serving as a powerful symbol of Ukrainian spiritual sovereignty. The church was led by Patriarch Filaret (Denisenko), who sought to consolidate the canonical status of Ukrainian Orthodoxy. While initially joining the unification movement that created the Orthodox Church of Ukraine (OCU) in 2018, the UOC-KP was later re-registered, asserting its continued legal existence as a distinct entity. The church regards itself as the legitimate successor to the ancient Metropolis of Kyiv. Despite complex canonical recognition issues within the global Eastern Orthodox community, the UOC-KP remained one of the largest Orthodox confessions in Ukraine. It performs all traditional Eastern Orthodox rites and services, providing deep spiritual life for its millions of faithful. We offer rites, accept prayer notes, and light candles according to the Byzantine tradition.',
                'de' => 'Die Ukrainisch-Orthodoxe Kirche des Kiewer Patriarchats (UOK-KP) wurde 1992 gegründet und führt ihr spirituelles Erbe auf die Christianisierung der Kiewer Rus im Jahr 988 zurück. Sie entstand nach einer Spaltung von der Russisch-Orthodoxen Kirche, motiviert durch den Wunsch nach einer vollständig unabhängigen, autokephalen ukrainischen Kirche. Der Hauptsitz der Kirche ist die historische St.-Wladimir-Kathedrale in Kiew, die ein starkes Symbol der ukrainischen geistlichen Souveränität darstellt. Die Kirche wurde von Patriarch Filaret (Denisenko) geleitet, der den kanonischen Status der ukrainischen Orthodoxie festigen wollte. Obwohl die UOK-KP ursprünglich der Einigungsbewegung beitrat, die 2018 die Orthodoxe Kirche der Ukraine (OKU) ins Leben rief, wurde sie später erneut registriert, um ihre fortgesetzte rechtliche Existenz als eigenständige Einheit zu bekräftigen. Die Kirche betrachtet sich als rechtmäßige Nachfolgerin der alten Metropolie von Kiew. Trotz komplexer Fragen der kanonischen Anerkennung in der globalen östlich-orthodoxen Gemeinschaft blieb die UOK-KP eine der größten orthodoxen Konfessionen in der Ukraine. Sie führt alle traditionellen östlich-orthodoxen Riten und Gottesdienste durch und bietet Millionen von Gläubigen ein tiefes geistliches Leben. Wir bieten Riten an, nehmen Gebetszettel entgegen und zünden Kerzen gemäß der byzantinischen Tradition an.',
                'ro' => 'Biserica Ortodoxă Ucraineană a Patriarhatului de Kiev (BOU-PK) a fost înființată în 1992, urmărindu-și moștenirea spirituală până la creștinarea Rusiei Kievene în anul 988. Aceasta a apărut în urma unei schisme cu Patriarhia Moscovei, motivată de dorința unei Biserici Ucrainene complet independente, autocefale. Sediul principal al bisericii este istorica Catedrală Sf. Vladimir din Kiev, servind ca un simbol puternic al suveranității spirituale ucrainene. Biserica a fost condusă de Patriarhul Filaret (Denisenko), care a căutat să consolideze statutul canonic al Ortodoxiei Ucrainene. Deși inițial s-a alăturat mișcării de unificare care a creat Biserica Ortodoxă a Ucrainei (BOU) în 2018, BOU-PK a fost ulterior reînregistrată, afirmându-și existența legală continuă ca entitate distinctă. Biserica se consideră succesoarea legitimă a vechii Mitropolii de Kiev. În ciuda problemelor complexe de recunoaștere canonică în comunitatea ortodoxă de Răsărit, BOU-PK a rămas una dintre cele mai mari confesiuni ortodoxe din Ucraina. Ea efectuează toate riturile și serviciile tradiționale ortodoxe de Răsărit. Oferim ritualuri, acceptăm bilețele de rugăciune și aprindem lumânări conform tradiției bizantine.',
                'ka' => 'კიევის საპატრიარქოს უკრაინის მართლმადიდებელი ეკლესია (УПЦ-КП) დაარსდა 1992 წელს და მის სულიერ მემკვიდრეობას 988 წელს კიევის რუსის გაქრისტიანებიდან იღებს. იგი მოსკოვის საპატრიარქოსთან განხეთქილების შედეგად გაჩნდა, რაც სრულად დამოუკიდებელი, ავტოკეფალური უკრაინული ეკლესიის შექმნის სურვილით იყო მოტივირებული. ეკლესიის დედა საყდარია ისტორიული ვლადიმირის ტაძარი კიევში, რომელიც უკრაინის სულიერი სუვერენიტეტის ძლიერ სიმბოლოდ გვევლინება. ეკლესიას ხელმძღვანელობდა პატრიარქი ფილარეტი (დენისენკო), რომელიც უკრაინული მართლმადიდებლობის კანონიკური სტატუსის განმტკიცებას ცდილობდა. მიუხედავად იმისა, რომ УПЦ-КП თავდაპირველად შეუერთდა გაერთიანების მოძრაობას, რომელმაც 2018 წელს უკრაინის მართლმადიდებელი ეკლესია (ПЦУ) შექმნა, ის მოგვიანებით ხელახლა დარეგისტრირდა და დაადასტურა თავისი ცალკე იურიდიული არსებობა. ეკლესია თავს კიევის უძველესი მიტროპოლიის ლეგიტიმურ მემკვიდრედ მიიჩნევს. გლობალურ აღმოსავლეთ მართლმადიდებლურ საზოგადოებაში კანონიკური აღიარების რთული საკითხების მიუხედავად, УПЦ-КП უკრაინაში ერთ-ერთ უდიდეს მართლმადიდებლურ კონფესიად დარჩა. იგი ასრულებს ყველა ტრადიციულ აღმოსავლეთ მართლმადიდებლურ წეს-ჩვეულებას. ჩვენ გთავაზობთ წეს-ჩვეულებებს, ვიღებთ სალოცავ ჩანაწერებს და ვანთებთ სანთლებს ბიზანტიური ტრადიციის მიხედვით.',
            ],
            'emoji' => '☦️',
            'active' => true,
        ]);
        // Attached to Ukraine, Germany, and Poland using their 'iso_3166_2' codes
        $confession1->countries()->attach(array_intersect_key($countries, array_flip(['UA', 'DE', 'PL'])));

        $confession2 = Confession::create([
            'name' => [
                'uk' => 'Свідки Єгови',
                'en' => 'Jehovah\'s Witnesses',
                'de' => 'Zeugen Jehovas',
                'ro' => 'Martorii lui Iehova',
                'ka' => 'იეჰოვას მოწმეები',
            ],
            'full_name' => [
                'uk' => 'Свідки Єгови',
                'en' => 'Jehovah\'s Witnesses',
                'de' => 'Zeugen Jehovas',
                'ro' => 'Martorii lui Iehova',
                'ka' => 'იეჰოვას მოწმეები',
            ],
            'description' => [
                'uk' => 'Свідки Єгови - це всесвітня християнська релігійна організація, що бере свій початок від руху Дослідників Біблії у США в 1870-х роках. Ця віра характеризується нетринітарними переконаннями, стверджуючи, що Бог, якого вони називають Єговою, є найвищим. Ісус Христос вважається Його Сином і посередником. Вони найбільш відомі своєю інтенсивною, організованою проповідницькою діяльністю, часто від дверей до дверей або через літературні стенди. Вони розповсюджують публікації, зокрема «Вартову башту» та «Пробудись!», перекладені понад 1000 мовами. Основна доктрина – це віра в те, що людство живе в «останні дні», які ведуть до Армагедону, що покладе початок Божому Царству на землі. Їхня практика наголошує на суворій відокремленості від світської влади. Це призводить до відмови від салютування національним прапорам, військової служби чи участі у виборах. Крім того, вони утримуються від переливання крові з релігійних міркувань і не святкують традиційні свята чи дні народження, вважаючи їх язичницькими нашаруваннями.',
                'en' => 'Jehovah\'s Witnesses are a global Christian religious organization that traces its origins to the Bible Student movement in the United States in the 1870s. This faith is characterized by its non-Trinitarian beliefs, asserting that God, whom they call Jehovah, is supreme, and Jesus Christ is his Son and agent, not part of a triune Godhead. Witnesses are best recognized globally for their intensive, organized evangelism, often conducted door-to-door or at literature stands in public places. They disseminate religious publications, primarily *The Watchtower* and *Awake!*, translated into over 1,000 languages. A core doctrine is the belief that humanity is living in the "last days" leading up to Armageddon, which will usher in God\'s Kingdom. Their practices stress strict separation from secular government, leading to refusal to salute national flags, participate in military service, or vote in public elections. Furthermore, they abstain from blood transfusions on religious grounds and do not celebrate traditional holidays or birthdays, viewing them as pagan accretions.',
                'de' => 'Jehovas Zeugen sind eine christliche Religionsgemeinschaft, deren Ursprünge auf die Bibelforscherbewegung in den Vereinigten Staaten in den 1870er Jahren zurückgehen. Dieser Glaube ist durch seine nontrinitarischen Überzeugungen gekennzeichnet, die besagen, dass Gott, den sie Jehova nennen, der Höchste ist und Jesus Christus sein Sohn und Stellvertreter ist, nicht Teil einer dreieinigen Gottheit. Zeugen Jehovas sind weltweit bekannt für ihre intensive, organisierte Evangelisationsarbeit, die oft von Tür zu Tür oder an Literaturständen an öffentlichen Orten durchgeführt wird. Sie verbreiten religiöse Publikationen, vor allem *Der Wachtturm* und *Erwachet!*, die in über 1.000 Sprachen übersetzt sind. Eine Kerndoktrin ist die Überzeugung, dass die Menschheit in den „letzten Tagen“ vor Harmagedon lebt, das Gottes Königreich einläuten wird. Ihre Praktiken betonen eine strikte Trennung von der weltlichen Regierung, was zur Weigerung führt, Nationalflaggen zu grüßen, Militärdienst zu leisten oder an öffentlichen Wahlen teilzunehmen. Darüber hinaus lehnen sie aus religiösen Gründen Bluttransfusionen ab und feiern keine traditionellen Feiertage oder Geburtstage, da sie diese als heidnische Anhängsel betrachten.',
                'ro' => 'Martorii lui Iehova sunt o organizație religioasă creștină globală care își are originile în mișcarea Studenților Bibliei din Statele Unite ale Americii, în anii 1870. Această credință se caracterizează prin convingerile sale netrinitare, afirmând că Dumnezeu, pe care Îl numesc Iehova, este suprem, iar Isus Hristos este Fiul Său și agentul Său, nu parte a unei Treimi. Martorii sunt cel mai bine recunoscuți la nivel global pentru lucrarea lor intensă și organizată de evanghelizare, adesea efectuată din ușă în ușă sau la standuri de literatură în locuri publice. Ei diseminează publicații religioase, în principal *Turnul de veghe* și *Treziți-vă!*, traduse în peste 1.000 de limbi. O doctrină centrală este credința că omenirea trăiește în „zilele din urmă” care duc la Armaghedon, care va inaugura Regatul lui Dumnezeu. Practicile lor subliniază separarea strictă de guvernul secular, ducând la refuzul de a saluta steagurile naționale, de a participa la serviciul militar sau de a vota la alegeri publice. În plus, ei se abțin de la transfuziile de sânge din motive religioase și nu celebrează sărbători tradiționale sau zile de naștere, considerându-le adăugiri păgâne.',
                'ka' => 'იეჰოვას მოწმეები არის გლობალური ქრისტიანული რელიგიური ორგანიზაცია, რომლის სათავე 1870-იანი წლების შეერთებულ შტატებში ბიბლიის შემსწავლელთა მოძრაობაშია. ამ რწმენას ახასიათებს მისი არატრინიტარული შეხედულებები, რომელიც ამტკიცებს, რომ ღმერთი, რომელსაც ისინი იეჰოვას უწოდებენ, უზენაესია, ხოლო იესო ქრისტე არის მისი ძე და შუამავალი, და არა სამეული ღვთაების ნაწილი. მოწმეები გლობალურად ცნობილი არიან თავიანთი ინტენსიური, ორგანიზებული ევანგელიზაციით, რომელიც ხშირად ტარდება კარდაკარ ან საჯარო ადგილებში ლიტერატურული სტენდების მეშვეობით. ისინი ავრცელებენ რელიგიურ პუბლიკაციებს, ძირითადად „საგუშაგო კოშკს“ და „გამოიღვიძეთ!“, რომლებიც თარგმნილია 1000-ზე მეტ ენაზე. ძირითადი დოქტრინაა რწმენა იმისა, რომ კაცობრიობა ცხოვრობს „ბოლო დღეებში“, რომელიც არმაგედონამდე მიდის და ღვთის სამეფოს დაამყარებს. მათი პრაქტიკა ხაზს უსვამს მკაცრ განცალკევებას საერო ხელისუფლებისგან, რაც იწვევს ეროვნული დროშებისადმი სალამების მიცემაზე, სამხედრო სამსახურში მონაწილეობაზე ან არჩევნებში ხმის მიცემაზე უარის თქმას. გარდა ამისა, ისინი რელიგიური მიზეზების გამო თავს იკავებენ სისხლის გადასხმისგან და არ აღნიშნავენ ტრადიციულ დღესასწაულებსა თუ დაბადების დღეებს, მათ წარმართულ დანამატებად მიიჩნევენ.',
            ],
            'emoji' => '📖',
            'active' => true,
        ]);
        // Attached only to Ukraine
        $confession2->countries()->attach($countries['UA'] ?? null);

        $confession3 = Confession::create([
            'name' => [
                'uk' => 'Греко-католицька церква',
                'en' => 'Greek Catholic Church',
                'de' => 'Griechisch-katholische Kirche',
                'ro' => 'Biserica Greco-Catolică',
                'ka' => 'ბერძნულ-კათოლიკური ეკლესია',
            ],
            'full_name' => [
                'uk' => 'Українська греко-католицька церква',
                'en' => 'Ukrainian Greek Catholic Church',
                'de' => 'Ukrainische griechisch-katholische Kirche',
                'ro' => 'Biserica Greco-Catolică Ucraineană',
                'ka' => 'უკრაინის ბერძნულ-კათოლიკური ეკლესია',
            ],
            'description' => [
                'uk' => 'Українська греко-католицька церква (УГКЦ) є найбільшою із Східних Католицьких Церков, що налічує понад 5.5 мільйона вірних по всьому світу. Ця унікальна Церква перебуває у повному канонічному сопричасті зі Святим Престолом, визнаючи Папу своїм духовним главою. Водночас вона зберігає стародавній візантійський літургійний обряд та відмінні культурні традиції. УГКЦ формально була заснована після Берестейської унії 1596 року, об’єднавши православних віруючих з Римом зі збереженням їхньої східної спадщини. Історично Церква відігравала вирішальну роль у збереженні національної та культурної ідентичності українського народу. Її відмінні практики включають наявність одруженого духовенства, що є поширеним у східнохристиянських традиціях. УГКЦ керується Синодом Єпископів та очолюється Верховним Архієпископом Київським і Галицьким. Церква реалізує низку благодійних та громадських проєктів як в Україні, так і за кордоном. Ми здійснюємо традиційні східно-католицькі служби, молебні та заупокійні служби суворо за канонами.',
                'en' => 'The Ukrainian Greek Catholic Church (UGCC) is the largest of the Eastern Catholic Churches, boasting over 5.5 million adherents worldwide. This unique Church is in full canonical communion with the Holy See, acknowledging the Pope as its spiritual head, yet it beautifully preserves the ancient Byzantine liturgical rite and distinct cultural traditions. The UGCC traces its formal establishment back to the Union of Brest-Litovsk in 1596, unifying Orthodox faithful with Rome while maintaining their Eastern heritage. Historically, the church played a vital role in preserving the national and cultural identity of the Ukrainian people, often operating underground, particularly during periods of persecution. Its distinct practices include having a married clergy, which is common in Eastern Christian traditions. The UGCC is governed by the Synod of Bishops and headed by the Major Archbishop of Kyiv and Halych. The church implements a range of charitable and civic projects both in Ukraine and abroad, demonstrating its commitment to social ministry. We offer traditional Eastern Catholic services, molébens, and memorial services strictly according to the canons.',
                'de' => 'Die Ukrainische Griechisch-Katholische Kirche (UGKK) ist die größte der Ostkatholischen Kirchen und zählt weltweit über 5,5 Millionen Anhänger. Diese einzigartige Kirche steht in voller kanonischer Gemeinschaft mit dem Heiligen Stuhl und erkennt den Papst als ihr geistliches Oberhaupt an. Gleichzeitig bewahrt sie den alten byzantinischen liturgischen Ritus und unterscheidbare kulturelle Traditionen. Die UGKK führt ihre formelle Gründung auf die Union von Brest im Jahr 1596 zurück, die orthodoxe Gläubige mit Rom vereinte, während sie ihr östliches Erbe beibehielt. Historisch spielte die Kirche eine entscheidende Rolle bei der Bewahrung der nationalen und kulturellen Identität des ukrainischen Volkes, oft im Untergrund tätig, insbesondere während Verfolgungszeiten. Zu ihren Besonderheiten gehört das verheiratete Klerus, was in östlichen christlichen Traditionen üblich ist. Die UGKK wird vom Bischofssynod geleitet und steht unter der Führung des Großerzbischofs von Kiew und Halitsch. Die Kirche führt eine Reihe von Wohltätigkeits- und Gemeinschaftsprojekten im In- und Ausland durch, was ihr Engagement für soziale Dienste beweist. Wir bieten traditionelle ostkatholische Gottesdienste, Bittgottesdienste und Totengedenken streng nach den Kanones an.',
                'ro' => 'Biserica Greco-Catolică Ucraineană (BGCC) este cea mai mare dintre Bisericile Catolice Orientale, cu peste 5,5 milioane de adepți la nivel mondial. Această Biserică unică este în comuniune canonică deplină cu Sfântul Scaun, recunoscând pe Papă ca șef spiritual, dar păstrează frumos vechiul rit liturgic bizantin și tradițiile culturale distincte. BGCC își trasează înființarea formală înapoi la Unirea de la Brest-Litovsk din 1596, unind credincioșii ortodocși cu Roma, menținându-le în același timp moștenirea orientală. Din punct de vedere istoric, biserica a jucat un rol vital în păstrarea identității naționale și culturale a poporului ucrainean, operând adesea în clandestinitate, în special în perioadele de persecuție. Practicile sale distincte includ existența unui cler căsătorit, care este obișnuit în tradițiile creștine orientale. BGCC este guvernată de Sinodul Episcopilor și condusă de Arhiepiscopul Major al Kievului și Haliței. Biserica implementează o serie de proiecte caritabile și civice atât în Ucraina, cât și în străinătate. Oferim slujbe tradiționale catolice orientale, rugăciuni și slujbe de pomenire în strictă conformitate cu canoanele.',
                'ka' => 'უკრაინის ბერძნულ-კათოლიკური ეკლესია (UGCC) არის უდიდესი აღმოსავლური კათოლიკური ეკლესიებიდან, რომელსაც მსოფლიოში 5.5 მილიონზე მეტი მიმდევარი ჰყავს. ეს უნიკალური ეკლესია იმყოფება სრულ კანონიკურ ერთობაში წმინდა საყდართან, აღიარებს პაპს თავის სულიერ წინამძღვრად, მაგრამ ლამაზად ინარჩუნებს ძველ ბიზანტიურ ლიტურგიულ წესს და განსხვავებულ კულტურულ ტრადიციებს. UGCC თავის ფორმალურ დაარსებას 1596 წლის ბრესტის კავშირს უკავშირებს, როდესაც მართლმადიდებელ მორწმუნეებს რომთან გაერთიანებისას შეუნარჩუნეს აღმოსავლური მემკვიდრეობა. ისტორიულად, ეკლესიამ სასიცოცხლო როლი ითამაშა უკრაინელი ხალხის ეროვნული და კულტურული იდენტობის შენარჩუნებაში, ხშირად მოქმედებდა იატაკქვეშეთში, განსაკუთრებით დევნის პერიოდებში. მის განმასხვავებელ პრაქტიკებში შედის დაქორწინებული სამღვდელოება, რაც აღმოსავლურ ქრისტიანულ ტრადიციებში გავრცელებულია. UGCC იმართება ეპისკოპოსთა სინოდის მიერ და ხელმძღვანელობს კიევისა და გალიჩის მთავარეპისკოპოსი. ეკლესია ახორციელებს რიგ საქველმოქმედო და სამოქალაქო პროექტებს როგორც უკრაინაში, ასევე საზღვარგარეთ. ჩვენ ვასრულებთ ტრადიციულ აღმოსავლურ კათოლიკურ მსახურებებს, მოსახვევებს და სამემორიალო მსახურებებს კანონების მკაცრი დაცვით.',
            ],
            'emoji' => '✝️',
            'active' => true,
        ]);
        // Attached to Ukraine and Romania
        $confession3->countries()->attach(array_intersect_key($countries, array_flip(['UA', 'RO'])));
    }
}
